### ISSUE TITLE
License for code snippets

### ISSUE THREAD

**Issue by jcubic** [jdan/thatjdanisso.cool#6]
What is the license for the code in articles? I would like to use https://thatjdanisso.cool/mandelbrot but there are no copyright information and no license.

I suggest any Creative Commons license for all your posts. You can pick share alike and/or no commercial if you prefer.

**Comment by jdan** [comment]
thanks so much for pointing this out (and asking!) lemme know if the footer info is sufficient.

**Comment by jcubic** [comment]
Thanks, this is perfect I can use the code and credit you with link to that page, even that the code is not visible.

If whole content of the blog is released on CC-BY-NC it's also worth adding LICENSE file to git repo or add it at the end of the README.

**Comment by jdan** [comment]
Done - thanks <3
